import "./globals.css";

export const metadata = {
  title: "What the Deps",
  description: "Generated by create next app",
  authors: [{ name: "Wiktoria van Harneveldt", url: "" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
